# Generated by Django 5.2.13 on 2026-05-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_batch_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesprocessing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('reserve', 'Reserve'), ('release', 'Release'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('daily_processing', 'Daily Sales Processing')], max_length=30),
        ),
    ]
