# Generated by Django 5.2.14 on 2026-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_dailysalesprocessing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
