# Generated by Django 5.2.14 on 2026-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0004_inventoryrecord_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='prevent_negative_stock'),
        ),
    ]
