# Generated by Django 5.2.13 on 2026-04-17 19:38

import apps.cart.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(default=apps.cart.models.default_cart_expiry),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ordered', 'Ordered'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
