# Generated by Django 5.2.13 on 2026-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('account_source', models.CharField(choices=[('self_registered', 'Self Registered'), ('admin_created', 'Admin Created'), ('imported', 'Imported')], default='self_registered', max_length=30)),
                ('must_set_password', models.BooleanField(default=False)),
                ('first_login_pending', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
